### ISSUE TITLE
Windows & LegUp 6.x

### ISSUE THREAD

**Issue by JohnnyOpcode** [danielholanda/LeFlow#11]
Need directions/guidance to bring LeFlow to Windows and LegUp 6.1 if possible.

J.

**Comment by danielholanda** [comment]
Hi,

I would recommend using virtual box and the provided virtual machine if you need to run things from a windows machine. LegUp 6.1 is a commercial version, so it is possible that you will not have access to the code to change what is needed to make LeFlow work.
