### ISSUE TITLE
LeFlow with new LegUP

### ISSUE THREAD

**Issue by najt-k** [danielholanda/LeFlow#17]
Hi, had you tried new LegUP (6.5) with LeFlow? I want use LeFlow on Xilinx board, what I know, that "commercialized" LegUP (https://www.legupcomputing.com) works on any FPGA.

**Comment by danielholanda** [comment]
Hi, we currently don't support the commercial version of LegUp. Integrating LeFlow into this version of  LegUp would require modifying their source code, which is not open-source.

**Comment by najt-k** [comment]
Do you plan support commercial version?

**Comment by danielholanda** [comment]
This is currently not something that we are planning on doing.
