### ISSUE TITLE
Are there any restrictions on the selection of FPGA version？

### ISSUE THREAD

**Issue by janyChan** [danielholanda/LeFlow#19]
If I will deploy the algorithm with LeFlow, the version of FPGA does have some restrictions ?
The Artix-7 of xilinx could be used?

**Comment by danielholanda** [comment]
Hi,

I believe that the answer to your question is already here https://github.com/danielholanda/LeFlow/issues/10.

Is short, LeFlow works with the boards that are supported by the open version of LegUp, which are Intel FPGAs. There is also the alternative to modify LegUp to support Xilinx devices, but we don't do that here.

**Comment by janyChan** [comment]
Thank you！
