### ISSUE TITLE
How to use LeFlow for custom graph

### ISSUE THREAD

**Issue by ChowderII** [danielholanda/LeFlow#28]
Hi again!

I have managed to successfully install LeFlow with the modified version of TensorFlow. I ran the run_test.py file with no errors. 

Now, I wrote a graph that I used for my research and I would like to transform it in hardware for testing. 

I get the following error:
legup@legup-vm:~/LeFlow/test$ ../../src/LeFlow my_model.py
INFO: Creating project...
INFO: Cleaning previous files...
INFO: Generating IR from tensorflow...
INFO: Cleaning unused dumped files...
Traceback (most recent call last):
File "../../src/LeFlow", line 195, in
run_leflow(args.file_name,tool_path)
File "../../src/LeFlow", line 79, in run_leflow
shutil.copy(project_folder+"ir/ir-cluster_0__XlaCompiledKernel_true__XlaNumConstantArgs_0__XlaNumResourceArgs_0__module-with-opt.ll",project_folder+project_name+"_ir_1.ll")
File "/usr/lib/python2.7/shutil.py", line 119, in copy
copyfile(src, dst)
File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'my_model_files/ir/ir-cluster_0__XlaCompiledKernel_true__XlaNumConstantArgs_0__XlaNumResourceArgs_0__module-with-opt.ll'

I have seen a few people with this error in the issues but I have not been able to fix my error with their solutions.

I can supply my code if necessary.

Thank you for your help!

**Comment by danielholanda** [comment]
Hi,

Sorry for the terrible delay replying to this.

For some reason it looks like there is a problem with the current version of Tensorflow. Try to uninstall this one and [use this old version](https://github.com/danielholanda/LeFlow/blob/7504ea9a5fcde898d6962eca5efbc5602bb522f2/src/tensorflow/tensorflow-1.6.0-cp27-cp27mu-linux_x86_64.whl) instead.
