### ISSUE TITLE
Access HDL code

### ISSUE THREAD

**Issue by mahdieghane** [danielholanda/LeFlow#41]
Hi, 
Hope you're well. I'm using your library and instruction for implementing a deep learning code on Xilinx. I became a luttle confused about your provided codes I'd be so grateful if you could help me. First, could you please let me know how can I install your library? Secondly, #import processMif as mif# line doesn't work, how can I fix that? I tried to change the version of the python, but nothing has changed. Also, after all of steps, how can I access HDL code?

Many thanks for your help in advance.

**Comment by danielholanda** [comment]
Sorry, for some reason I missed that you created this issue. 
The instructions for installing and testing LeFlow can be found here:
https://github.com/danielholanda/LeFlow/blob/master/README.md
