### ISSUE TITLE
IOError: [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by mahinlman** [danielholanda/LeFlow#7]
When I tried to run maxpoolingMNIST.py, I got below mentioned error

legup@legup-vm:~/LeFlow/examples/maxpoolMNIST$ ../../src/LeFlow maxpoolMNIST.py INFO: Creating project...
INFO: Cleaning previous files...
INFO: Generating IR from tensorflow...
INFO: Cleaning unused dumped files...
Traceback (most recent call last):
  File "../../src/LeFlow", line 200, in <module>
    run_leflow(args.file_name,tool_path)
  File "../../src/LeFlow", line 79, in run_leflow
    shutil.copy(project_folder+"ir/ir-cluster_0__XlaCompiledKernel_true__XlaNumConstantArgs_0__XlaNumResourceArgs_0__module-with-opt.ll",project_folder+project_name+"_ir_1.ll")
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'maxpoolMNIST_files/ir/ir-cluster_0__XlaCompiledKernel_true__XlaNumConstantArgs_0__XlaNumResourceArgs_0__module-with-opt.ll'

**Comment by santacml** [comment]
Do you know what caused this? I am getting the same issue.

I am trying to use maxpooling in a different application and that is not working either. It seems maxpooling is not working?

**Comment by danielholanda** [comment]
This is now being discussed at https://github.com/danielholanda/LeFlow/issues/13

**Comment by SAB95852** [comment]
I have the same issue
